from distutils.core import setup   
setup(name = 'awspy',
	  packages = ['awspy',
				  'awspy.utils',
	              'awspy.delegate',
	              'awspy.ftp',
	              'awspy.http',
	              'awspy.nt',
	              'awspy.object',
	              'awspy.socket',
	              'awspy.zip',
	              ],
#	  packages = find_packages('src'), 
	  package_dir = {'' : 'src'},
	  version = '1.0.3',
	  description = 'the product of artwebs',
	  author='artwebs',   
     ) 