from distutils.core import setup
setup(name = 'awspy',
	  packages = ['awspy',
				  'awspy.Utils',
                  'awspy.action',
                  'awspy.database',
                  'awspy.database.redisco',
                  'awspy.database.redisco.models',
	              'awspy.delegate',
	              'awspy.ftp',
	              'awspy.http',
                  'awspy.log',
	              'awspy.nt',
	              'awspy.object',
                  'awspy.security',
	              'awspy.socket',
	              'awspy.zip',
	              ],
#	  packages = find_packages('src'),
	  version = '1.0.6',
	  description = 'the product of artwebs',
	  author='artwebs',   
     ) 